export enum LABELS {
    // Direct route
    DIRECT_OUTBOUND = 'DIRECT_OUTBOUND',
    DIRECT_INBOUND = 'DIRECT_INBOUND',

    // Alternative route
    ALT_OUTBOUND_LEG1 = 'ALT_OUTBOUND_LEG1',
    ALT_OUTBOUND_LEG2 = 'ALT_OUTBOUND_LEG2',
    ALT_INBOUND_LEG1 = 'ALT_INBOUND_LEG1',
    ALT_INBOUND_LEG2 = 'ALT_INBOUND_LEG2',
}

export enum PATTERN {
    DIRECT_ROUTE = 'DIRECT_ROUTE',
    ALTERNATIVE_ROUTE = 'ALTERNATIVE_ROUTE',
}

export const TOP_FLIGHTS_TO_COLLECT_LIMIT = 3;

export const RESULTS_KEY = 'flight-results';
