export enum LABELS {
    SEARCH_OUTBOUND = 'SEARCH_OUTBOUND',
    SEARCH_INBOUND = 'SEARCH_INBOUND',
}

export enum PATTERN {
    DIRECT_ROUTE = 'DIRECT_ROUTE',
    ALTERNATIVE_ROUTE = 'ALTERNATIVE_ROUTE',
}

export const TOP_FLIGHTS_TO_COLLECT_LIMIT = 3;

export const RESULTS_KEY = 'flight-results';
