export const LABELS = {
    START: 'START',
    OUT_BOUND: 'OUT_BOUND',
    IN_BOUND: 'IN_BOUND',
};

export enum PATTERN {
    DIRECT_ROUTE = 'DIRECT_ROUTE',
    ALTERNATIVE_ROUTE = 'ALTERNATIVE_ROUTE',
}

export enum ALTERNATIVE_ROUTE_STEPS {
    TO_INTERMEDIATE = 'TO_INTERMEDIATE',
    INTERMEDIATE_TO_TARGET = 'INTERMEDIATE_TO_TARGET',
}
